apiVersion: v1
kind: Service
metadata:
  name: quilr-backend
  namespace: quilr-onboard
spec:
  selector:
    app: quilr-backend
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 8000
