apiVersion: apps/v1
kind: Deployment
metadata:
  name: quilr-frontend
  namespace: quilr-onboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quilr-frontend
  template:
    metadata:
      labels:
        app: quilr-frontend
    spec:
      containers:
        - name: web
          image: localhost:32000/quilr-onboard-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TLS_CERT_PATH
              value: /tls/tls.crt
            - name: TLS_KEY_PATH
              value: /tls/tls.key
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: quilr-onboard-tls
