apiVersion: v1
kind: Service
metadata:
  name: quilr-frontend
  namespace: quilr-onboard
spec:
  selector:
    app: quilr-frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
