apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quilr-onboard
  namespace: quilr-onboard
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
    - secretName: quilr-onboard-tls
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: quilr-backend
                port:
                  number: 8000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: quilr-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quilr-frontend
                port:
                  number: 3000
