apiVersion: v1
kind: Secret
metadata:
  name: quilr-onboard-secrets
  namespace: quilr-onboard
type: Opaque
stringData:
  SESSION_SECRET: change-me
  MS_CLIENT_ID: your-client-id
  MS_CLIENT_SECRET: your-client-secret
